# Generated by Django 5.2.8 on 2026-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querycache",
            name="invalidated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="querycache",
            name="negative_feedback",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="querycache",
            name="positive_feedback",
            field=models.IntegerField(default=0),
        ),
    ]
